/* Standalone host test for the runtime asset loader (runtime_assets.c).
 *
 * Exercises it against a real generated fixture (src/data/tests/fixtures/,
 * packed by `ebtools pack assets` / generated by `ebtools embed-registry
 * --runtime`, see CMakeLists.txt) so the Python codegen and the C loader
 * are checked against each other without needing a ROM. Covers the happy
 * path plus every EbAssetLoadResult failure mode by mutating a copy of the
 * valid pak's bytes.
 *
 * Usage: test_runtime_assets <valid_pak_path> <scratch_dir>
 */
#include "runtime_assets.h"

#include "asset_ids.h"
#include "embedded_assets.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* .pak layout constants, mirrored from runtime_assets.c / docs/assets.md
 * (kept independent on purpose, this test is meant to catch drift in
 * either side). */
#define PAK_HEADER_SIZE 44u
#define PAK_INDEX_ENTRY_SIZE 8u

static int g_failures = 0;

#define CHECK(cond, msg)                                                    \
    do {                                                                    \
        if (!(cond)) {                                                      \
            fprintf(stderr, "FAIL: %s (%s:%d)\n", msg, __FILE__, __LINE__); \
            g_failures++;                                                   \
        }                                                                   \
    } while (0)

static unsigned char *read_whole_file(const char *path, long *out_size) {
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        perror("fopen (fixture pak)");
        exit(2);
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *buf = malloc((size_t)size);
    if (buf == NULL || fread(buf, 1, (size_t)size, f) != (size_t)size) {
        fprintf(stderr, "failed to read fixture pak\n");
        exit(2);
    }
    fclose(f);
    *out_size = size;
    return buf;
}

static void write_whole_file(const char *path, const unsigned char *data, size_t size) {
    FILE *f = fopen(path, "wb");
    if (f == NULL || fwrite(data, 1, size, f) != size) {
        fprintf(stderr, "failed to write %s\n", path);
        exit(2);
    }
    fclose(f);
}

/* Writes a byte-mutated copy of the valid pak to mutated_path and attempts
 * to load it, returning the result. `mutate` may be NULL to just truncate
 * to `truncate_to` bytes (pass (size_t)-1 to keep full size). */
static EbAssetLoadResult try_mutation(
    const unsigned char *valid_bytes,
    long valid_size,
    const char *mutated_path,
    size_t truncate_to,
    void (*mutate)(unsigned char *)
) {
    size_t size = (truncate_to == (size_t)-1) ? (size_t)valid_size : truncate_to;
    unsigned char *copy = malloc((size_t)valid_size);
    memcpy(copy, valid_bytes, (size_t)valid_size);
    if (mutate != NULL) {
        mutate(copy);
    }
    write_whole_file(mutated_path, copy, size);
    free(copy);
    EbAssetLoadResult result = eb_runtime_assets_load(mutated_path);
    CHECK(!eb_runtime_assets_ready(), "not ready after a failed load");
    return result;
}

static void mutate_bad_magic(unsigned char *b) { b[0] = 'X'; }
static void mutate_version(unsigned char *b) { b[4] = 99; }
static void mutate_hash(unsigned char *b) { b[12] ^= 0xFF; }
static void mutate_count(unsigned char *b) { b[8] += 1; }
static void mutate_index_overflow(unsigned char *b) {
    /* Asset 0's length field (index entry 0 is offset[0:4], length[4:8]) */
    b[PAK_HEADER_SIZE + 4] = 0xFF;
    b[PAK_HEADER_SIZE + 5] = 0xFF;
    b[PAK_HEADER_SIZE + 6] = 0xFF;
    b[PAK_HEADER_SIZE + 7] = 0x7F;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: %s <valid_pak_path> <scratch_dir>\n", argv[0]);
        return 2;
    }
    const char *valid_path = argv[1];
    const char *scratch_dir = argv[2];
    char mutated_path[1024];
    snprintf(mutated_path, sizeof(mutated_path), "%s/mutated.pak", scratch_dir);

    long valid_size;
    unsigned char *valid_bytes = read_whole_file(valid_path, &valid_size);

    /* happy path: fixture content from src/data/tests/fixtures/ */
    CHECK(eb_runtime_assets_load(valid_path) == EB_ASSETS_OK, "load valid pak");
    CHECK(eb_runtime_assets_ready(), "ready after load");

    CHECK(ASSET_DATA_FOO_BIN_DATA != NULL, "foo data non-null");
    CHECK(ASSET_DATA_FOO_BIN_SIZE == 9, "foo size");
    CHECK(memcmp(ASSET_DATA_FOO_BIN_DATA, "foo-bytes", 9) == 0, "foo bytes");

    CHECK(ASSET_DATA_BAR_BIN_SIZE == 16, "bar size");
    CHECK(memcmp(ASSET_DATA_BAR_BIN_DATA, "bar-bytes-longer", 16) == 0, "bar bytes");

    /* Locale alias: US/data/greeting.bin, reachable via the unprefixed name. */
    CHECK(ASSET_DATA_GREETING_BIN_SIZE == 5, "greeting size");
    CHECK(memcmp(ASSET_DATA_GREETING_BIN_DATA, "hello", 5) == 0, "greeting bytes");

    /* Family, including the gap at index 2. */
    CHECK(ASSET_MAPS_PALETTES_SIZE(0) == 32, "palette 0 size");
    CHECK(ASSET_MAPS_PALETTES_DATA(0)[0] == 0x00, "palette 0 byte");
    CHECK(ASSET_MAPS_PALETTES_DATA(1)[0] == 0x01, "palette 1 byte");
    CHECK(ASSET_MAPS_PALETTES_DATA(3)[0] == 0x03, "palette 3 byte");
    CHECK(ASSET_MAPS_PALETTES_DATA(2) == NULL, "palette 2 (gap) data is null");
    CHECK(ASSET_MAPS_PALETTES_SIZE(2) == 0, "palette 2 (gap) size is zero");

    eb_runtime_assets_unload();
    CHECK(!eb_runtime_assets_ready(), "not ready after unload");
    CHECK(ASSET_DATA_FOO_BIN_DATA == NULL, "foo data null after unload");
    CHECK(ASSET_DATA_FOO_BIN_SIZE == 0, "foo size zero after unload");

    /* failure paths */
    CHECK(eb_runtime_assets_load("/nonexistent/path/assets.pak") == EB_ASSETS_MISSING, "missing file");

    CHECK(try_mutation(valid_bytes, valid_size, mutated_path, (size_t)-1, mutate_bad_magic) == EB_ASSETS_BAD_MAGIC,
          "bad magic");
    CHECK(
        try_mutation(valid_bytes, valid_size, mutated_path, (size_t)-1, mutate_version) == EB_ASSETS_VERSION_MISMATCH,
        "version mismatch"
    );
    CHECK(try_mutation(valid_bytes, valid_size, mutated_path, (size_t)-1, mutate_hash) == EB_ASSETS_LAYOUT_MISMATCH,
          "layout hash mismatch");
    CHECK(try_mutation(valid_bytes, valid_size, mutated_path, (size_t)-1, mutate_count) == EB_ASSETS_COUNT_MISMATCH,
          "asset count mismatch");
    CHECK(
        try_mutation(valid_bytes, valid_size, mutated_path, PAK_HEADER_SIZE + 3 * PAK_INDEX_ENTRY_SIZE, NULL)
            == EB_ASSETS_IO_ERROR,
        "truncated (index table cut off)"
    );
    CHECK(
        try_mutation(valid_bytes, valid_size, mutated_path, (size_t)-1, mutate_index_overflow) == EB_ASSETS_IO_ERROR,
        "corrupt index entry (offset+length past blob)"
    );

    /* the loader must recover cleanly after a string of failures */
    CHECK(eb_runtime_assets_load(valid_path) == EB_ASSETS_OK, "reload valid pak after failures");
    CHECK(eb_runtime_assets_ready(), "ready after reload");
    CHECK(memcmp(ASSET_DATA_FOO_BIN_DATA, "foo-bytes", 9) == 0, "foo bytes correct after reload");
    eb_runtime_assets_unload();

    free(valid_bytes);

    if (g_failures == 0) {
        printf("test_runtime_assets: all checks passed\n");
        return 0;
    }
    fprintf(stderr, "test_runtime_assets: %d check(s) failed\n", g_failures);
    return 1;
}
