/* Auto-generated by ebtools embed-registry - do not edit */

#include "asset_ids.h"
#include "embedded_assets.h"
#include "asset_pack_layout.h"

/* Storage for the runtime-populated tables declared `extern` in
 * embedded_assets.h / asset_ids.h. Zero-initialized; the runtime
 * loader fills these in (eb_runtime_assets_load() then this file's
 * eb_runtime_assets_populate_families()). */
AssetEntry embedded_assets[ASSET_COUNT];
AssetFamilyEntry asset_family_audiopacks[169];
AssetFamilyEntry asset_family_battle_bgs_arrangements[103];
AssetFamilyEntry asset_family_battle_bgs_graphics[103];
AssetFamilyEntry asset_family_battle_bgs_palettes[114];
AssetFamilyEntry asset_family_battle_sprites[110];
AssetFamilyEntry asset_family_battle_sprites_palettes[32];
AssetFamilyEntry asset_family_maps_anim_gfx[20];
AssetFamilyEntry asset_family_maps_anim_pal[8];
AssetFamilyEntry asset_family_maps_anim_props[20];
AssetFamilyEntry asset_family_maps_arrangements[20];
AssetFamilyEntry asset_family_maps_gfx[20];
AssetFamilyEntry asset_family_maps_palettes[32];
AssetFamilyEntry asset_family_overworld_sprites_banks[5];
AssetFamilyEntry asset_family_overworld_sprites_palettes[8];
AssetFamilyEntry asset_family_psianims_arrangements[34];
AssetFamilyEntry asset_family_psianims_gfx[4];
AssetFamilyEntry asset_family_psianims_palettes[34];
AssetFamilyEntry asset_family_swirls[126];
AssetFamilyEntry asset_family_town_maps[6];

void eb_runtime_assets_populate_families(void) {
    for (unsigned i = 0; i < 169u; i++) { /* audiopacks/.ebm */
        asset_family_audiopacks[i].data = embedded_assets[ASSET_AUDIOPACKS_0_EBM + i].data;
        asset_family_audiopacks[i].size_ptr = embedded_assets[ASSET_AUDIOPACKS_0_EBM + i].size_ptr;
    }
    for (unsigned i = 0; i < 103u; i++) { /* battle_bgs/arrangements/.arr.lzhal */
        asset_family_battle_bgs_arrangements[i].data = embedded_assets[ASSET_BATTLE_BGS_ARRANGEMENTS_0_ARR_LZHAL + i].data;
        asset_family_battle_bgs_arrangements[i].size_ptr = embedded_assets[ASSET_BATTLE_BGS_ARRANGEMENTS_0_ARR_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 103u; i++) { /* battle_bgs/graphics/.gfx.lzhal */
        asset_family_battle_bgs_graphics[i].data = embedded_assets[ASSET_BATTLE_BGS_GRAPHICS_0_GFX_LZHAL + i].data;
        asset_family_battle_bgs_graphics[i].size_ptr = embedded_assets[ASSET_BATTLE_BGS_GRAPHICS_0_GFX_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 114u; i++) { /* battle_bgs/palettes/.pal */
        asset_family_battle_bgs_palettes[i].data = embedded_assets[ASSET_BATTLE_BGS_PALETTES_0_PAL + i].data;
        asset_family_battle_bgs_palettes[i].size_ptr = embedded_assets[ASSET_BATTLE_BGS_PALETTES_0_PAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 110u; i++) { /* battle_sprites/.gfx.lzhal */
        asset_family_battle_sprites[i].data = embedded_assets[ASSET_BATTLE_SPRITES_0_GFX_LZHAL + i].data;
        asset_family_battle_sprites[i].size_ptr = embedded_assets[ASSET_BATTLE_SPRITES_0_GFX_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 32u; i++) { /* battle_sprites/palettes/.pal */
        asset_family_battle_sprites_palettes[i].data = embedded_assets[ASSET_BATTLE_SPRITES_PALETTES_0_PAL + i].data;
        asset_family_battle_sprites_palettes[i].size_ptr = embedded_assets[ASSET_BATTLE_SPRITES_PALETTES_0_PAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 20u; i++) { /* maps/anim_gfx/.gfx.lzhal */
        asset_family_maps_anim_gfx[i].data = embedded_assets[ASSET_MAPS_ANIM_GFX_0_GFX_LZHAL + i].data;
        asset_family_maps_anim_gfx[i].size_ptr = embedded_assets[ASSET_MAPS_ANIM_GFX_0_GFX_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 8u; i++) { /* maps/anim_pal/.pal.lzhal */
        asset_family_maps_anim_pal[i].data = embedded_assets[ASSET_MAPS_ANIM_PAL_1_PAL_LZHAL + i].data;
        asset_family_maps_anim_pal[i].size_ptr = embedded_assets[ASSET_MAPS_ANIM_PAL_1_PAL_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 20u; i++) { /* maps/anim_props/.bin */
        asset_family_maps_anim_props[i].data = embedded_assets[ASSET_MAPS_ANIM_PROPS_0_BIN + i].data;
        asset_family_maps_anim_props[i].size_ptr = embedded_assets[ASSET_MAPS_ANIM_PROPS_0_BIN + i].size_ptr;
    }
    for (unsigned i = 0; i < 20u; i++) { /* maps/arrangements/.arr.lzhal */
        asset_family_maps_arrangements[i].data = embedded_assets[ASSET_MAPS_ARRANGEMENTS_0_ARR_LZHAL + i].data;
        asset_family_maps_arrangements[i].size_ptr = embedded_assets[ASSET_MAPS_ARRANGEMENTS_0_ARR_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 20u; i++) { /* maps/gfx/.gfx.lzhal */
        asset_family_maps_gfx[i].data = embedded_assets[ASSET_MAPS_GFX_0_GFX_LZHAL + i].data;
        asset_family_maps_gfx[i].size_ptr = embedded_assets[ASSET_MAPS_GFX_0_GFX_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 32u; i++) { /* maps/palettes/.pal */
        asset_family_maps_palettes[i].data = embedded_assets[ASSET_MAPS_PALETTES_0_PAL + i].data;
        asset_family_maps_palettes[i].size_ptr = embedded_assets[ASSET_MAPS_PALETTES_0_PAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 5u; i++) { /* overworld_sprites/banks/.bin */
        asset_family_overworld_sprites_banks[i].data = embedded_assets[ASSET_OVERWORLD_SPRITES_BANKS_11_BIN + i].data;
        asset_family_overworld_sprites_banks[i].size_ptr = embedded_assets[ASSET_OVERWORLD_SPRITES_BANKS_11_BIN + i].size_ptr;
    }
    for (unsigned i = 0; i < 8u; i++) { /* overworld_sprites/palettes/.pal */
        asset_family_overworld_sprites_palettes[i].data = embedded_assets[ASSET_OVERWORLD_SPRITES_PALETTES_0_PAL + i].data;
        asset_family_overworld_sprites_palettes[i].size_ptr = embedded_assets[ASSET_OVERWORLD_SPRITES_PALETTES_0_PAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 34u; i++) { /* psianims/arrangements/.arr.bundled */
        asset_family_psianims_arrangements[i].data = embedded_assets[ASSET_PSIANIMS_ARRANGEMENTS_0_ARR_BUNDLED + i].data;
        asset_family_psianims_arrangements[i].size_ptr = embedded_assets[ASSET_PSIANIMS_ARRANGEMENTS_0_ARR_BUNDLED + i].size_ptr;
    }
    for (unsigned i = 0; i < 4u; i++) { /* psianims/gfx/.gfx.lzhal */
        asset_family_psianims_gfx[i].data = embedded_assets[ASSET_PSIANIMS_GFX_0_GFX_LZHAL + i].data;
        asset_family_psianims_gfx[i].size_ptr = embedded_assets[ASSET_PSIANIMS_GFX_0_GFX_LZHAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 34u; i++) { /* psianims/palettes/.pal */
        asset_family_psianims_palettes[i].data = embedded_assets[ASSET_PSIANIMS_PALETTES_00_PAL + i].data;
        asset_family_psianims_palettes[i].size_ptr = embedded_assets[ASSET_PSIANIMS_PALETTES_00_PAL + i].size_ptr;
    }
    for (unsigned i = 0; i < 126u; i++) { /* swirls/.swirl */
        asset_family_swirls[i].data = embedded_assets[ASSET_SWIRLS_0_SWIRL + i].data;
        asset_family_swirls[i].size_ptr = embedded_assets[ASSET_SWIRLS_0_SWIRL + i].size_ptr;
    }
    for (unsigned i = 0; i < 6u; i++) { /* town_maps/.bin.lzhal */
        asset_family_town_maps[i].data = embedded_assets[ASSET_TOWN_MAPS_0_BIN_LZHAL + i].data;
        asset_family_town_maps[i].size_ptr = embedded_assets[ASSET_TOWN_MAPS_0_BIN_LZHAL + i].size_ptr;
    }
}
