/* Auto-generated by ebtools embed-registry - do not edit */

#ifndef ASSET_PACK_LAYOUT_H
#define ASSET_PACK_LAYOUT_H

#define ASSET_PACK_LAYOUT_HASH "c1499cc8d8c5edda0ba9e3c082b0cc470ea3d1e1babf896af0b8fa21c62e4b2a"

/* Populates every asset_family_* array from embedded_assets[], which
 * must already be populated (see eb_runtime_assets_load()). */
void eb_runtime_assets_populate_families(void);

#endif /* ASSET_PACK_LAYOUT_H */
