/* Auto-generated by ebtools embed-registry - do not edit */

#ifndef ASSET_PACK_LAYOUT_H
#define ASSET_PACK_LAYOUT_H

#define ASSET_PACK_LAYOUT_HASH "9aab83b7ad61ff2ed197c0cf6b153425226ce8616fcf077be83e1abe9d7657c2"

/* Populates every asset_family_* array from embedded_assets[], which
 * must already be populated (see eb_runtime_assets_load()). */
void eb_runtime_assets_populate_families(void);

#endif /* ASSET_PACK_LAYOUT_H */
