/* Auto-generated by ebtools embed-registry - do not edit */

#ifndef ASSET_PACK_HASH_H
#define ASSET_PACK_HASH_H

#define ASSET_PACK_LAYOUT_HASH "9aab83b7ad61ff2ed197c0cf6b153425226ce8616fcf077be83e1abe9d7657c2"

#endif /* ASSET_PACK_HASH_H */
