/* Auto-generated by ebtools embed-registry - do not edit */
#ifndef EMBEDDED_ASSETS_H
#define EMBEDDED_ASSETS_H

#include "asset_ids.h"

/* Asset entry: data pointer + pointer to a size variable. In the
 * compile-time-embed build both fields are link-time constants
 * (INCBIN); in an EB_RUNTIME_ASSETS build they're populated by
 * eb_runtime_assets_load() before first use. */
typedef struct {
    const unsigned char *data;
    const unsigned int *size_ptr;
} AssetEntry;

extern AssetEntry embedded_assets[ASSET_COUNT];

#endif /* EMBEDDED_ASSETS_H */
