/* Auto-generated by ebtools embed-registry - do not edit */

#ifndef ROM_EXTRACT_TABLE_H
#define ROM_EXTRACT_TABLE_H

#include <stdint.h>
#include "asset_ids.h"

#define ROM_IDENTIFIER "EARTH BOUND          "
#define ROM_SIZE 3145728u

typedef struct {
    uint32_t rom_offset;
    uint32_t rom_size;  /* 0 means this asset has no ROM-derived source (a family gap) */
} RomExtractEntry;

extern const RomExtractEntry rom_extract_table[ASSET_COUNT];

/* Source .arr.lzhal ranges for the 34 PSI arrangements (see
 * ebtools/parsers/psi_arrangements.py). These never appear in
 * rom_extract_table[] -- the final asset is the *bundled* form,
 * built from these at runtime by rom_extract.c (decompress, split
 * into 8-frame chunks, re-encode each chunk). */
#define PSI_ARRANGEMENT_COUNT 34
extern const RomExtractEntry psi_arrangement_source[PSI_ARRANGEMENT_COUNT];

#endif /* ROM_EXTRACT_TABLE_H */
