/* Auto-generated by ebtools embed-registry - do not edit */

#ifndef ROM_EXTRACT_TABLE_H
#define ROM_EXTRACT_TABLE_H

#include <stdint.h>
#include "asset_ids.h"

#define ROM_IDENTIFIER "EARTH BOUND          "
#define ROM_SIZE 3145728u

typedef struct {
    uint32_t rom_offset;
    uint32_t rom_size;  /* 0 means this asset has no ROM-derived source (a family gap) */
} RomExtractEntry;

extern const RomExtractEntry rom_extract_table[ASSET_COUNT];

#endif /* ROM_EXTRACT_TABLE_H */
