#ifndef DATA_ROM_EXTRACT_H
#define DATA_ROM_EXTRACT_H

/* Builds assets.pak straight from a donor ROM, no ebtools/Python involved.
 *
 * Only compiled when EB_RUNTIME_ASSETS is defined. Pairs with
 * src/data/runtime_assets.c's loader: this writes the exact same EBPK
 * format that loader reads. Uses rom_extract_table.c (generated by
 * `ebtools embed-registry --runtime`, see docs/assets.md) to know where
 * each asset lives in the ROM. Pure byte copies -- no decompression, since
 * assets are stored (and stay) exactly as compressed/raw as the ROM has
 * them; decomp() already runs at point-of-use elsewhere in the game, same
 * as a compile-time INCBIN build. */

typedef enum {
    EB_ROM_EXTRACT_OK = 0,
    EB_ROM_EXTRACT_IO_ERROR,     /* couldn't read the ROM file */
    EB_ROM_EXTRACT_TOO_SMALL,    /* file too small to be a real ROM */
    EB_ROM_EXTRACT_NOT_MATCHED,  /* checksum/title didn't match this game */
    EB_ROM_EXTRACT_WRITE_FAILED, /* couldn't write the output pak */
} EbRomExtractResult;

/* Slices rom_path per rom_extract_table[] and writes an EBPK-format pak to
 * out_path (creating parent directories as needed), written atomically via
 * a temp file + rename so a reader never sees a partial pak. */
EbRomExtractResult rom_extract_build_pak(const char *rom_path, const char *out_path);

/* Scans `dir` (non-recursive) for any .sfc/.smc file and tries each one
 * against rom_extract_build_pak() until one matches -- the ROM's own
 * checksum/title check (not the filename) decides what's a real match, so
 * this works no matter what the player named their ROM file. Returns
 * EB_ROM_EXTRACT_OK on the first match (pak written to out_path).
 * EB_ROM_EXTRACT_NOT_MATCHED if the directory had .sfc/.smc files but none
 * matched. EB_ROM_EXTRACT_IO_ERROR if the directory couldn't be scanned or
 * had no .sfc/.smc files at all -- callers should treat that the same as
 * "no ROM found" (there was nothing to try). */
EbRomExtractResult rom_extract_scan_and_build_pak(const char *dir, const char *out_path);

#endif /* DATA_ROM_EXTRACT_H */
